version: '3.5'
services:
    postgres:
        image: postgres:14-bookworm
        container_name: postgres
        command: postgres -c 'max_connections=200'
        restart: unless-stopped
        environment:
            POSTGRES_USER: "admin"
            POSTGRES_PASSWORD: "P@ssw0rd"
            POSTGRES_DB: "InventoryDW"
            #PGADMIN_SERVER_JSON_FILE: "./servers.json"
        ports:
            - 5432:5432
        volumes:
          #- postgres-db-volume:/var/lib/postgresql/data
          - ./postgres-db:/var/lib/postgresql/data
        networks:
           - postgres-net
    # pgadmin4:
    #     image: dpage/pgadmin4
    #     container_name: pgadmin4
    #     restart: always
    #     environment: 
    #         PGADMIN_DEFAULT_EMAIL: "admin@localhost.com"
    #         PGADMIN_DEFAULT_PASSWORD: "admin"
    #     ports: 
    #         - 8080:80
    #     networks: 
    #         - postgresql
# volumes:
#     postgres-db-volume:
#         name: postgres-db-volume
networks:
    postgres-net:
        name: postgres-net
        driver: bridge