services:
    postgres:
        image: postgres:18-trixie # trixie = Debian13
        container_name: postgres
        command: postgres -c 'max_connections=200'
        #restart: unless-stopped # uncomment if needed
        environment:
            POSTGRES_USER: "admin"
            POSTGRES_PASSWORD: "P@ssw0rd"
            POSTGRES_DB: "DWH"
        ports:
            - 5432:5432
        volumes:
            - ./postgres-db:/var/lib/postgresql
        networks:
            - postgres-net
    pgadmin4:
        image: dpage/pgadmin4:9
        container_name: pgadmin4
        #restart: unless-stopped # uncomment if needed
        environment: 
            PGADMIN_DEFAULT_EMAIL: "admin@local.com"
            PGADMIN_DEFAULT_PASSWORD: "admin"
        ports: 
            - 8081:80
        volumes:
            - ./pgadmin4:/var/lib/pgadmin
        networks: 
            - postgres-net
networks:
    postgres-net:
        name: postgres-net
        driver: bridge
